/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useCubeTexture } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("../images/GPR.glb");

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve.geometry}
        position={[0, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={18}
      >
        <meshStandardMaterial metalness={.1} roughness={.4} color={0x3c8323} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/GPR.glb");
